apiVersion: v1
kind: ResourceQuota
metadata:
  name: bigdata-quota
  namespace: bigdata-lab1
spec:
  hard:
    requests.cpu: "2"
    limits.cpu: "4"
    requests.memory: 2Gi
    limits.memory: 4Gi
    requests.storage: 8Gi
    persistentvolumeclaims: "2"
    pods: "10"
