apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs
  namespace: bigdata-lab1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seaweedfs
  template:
    metadata:
      labels:
        app: seaweedfs
    spec:
      containers:
        - name: seaweedfs
          image: chrislusf/seaweedfs:latest
          args:
            - server
            - -dir=/data
            - -s3
            - -s3.port=8333
          ports:
            - name: s3
              containerPort: 8333
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: seaweedfs-data
